name: dart_pub
description: A sample project
version: 0.0.0

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  uuid_enhanced: any
  perfectionist: any
  graphql_client: any
  icu: any
  image_picker_modern: any
